[package]
name = "handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interfaces = { path = "../../libs/interfaces" }
message_structure = { path = "../../libs/message_structure" }
common = { path = "../../libs/common" }