[workspace]

members = [
    "handlers/handler",
    "libs/interfaces",
    "message_dispatcher",
    "libs/message_structure",
    "scheduler",
    "handlers/dfgm_handler",
    "libs/common", 
    "ipc_testing/cli_test_msg", 
    "ipc_testing/ipc_client_test",
]
