[workspace]

members = [
    "handlers/handler",
    "libs/interfaces",
    "message_dispatcher",
    "libs/message_structure",
    "scheduler",
    "handlers/dfgm_handler",
    "libs/common", "handlers/bulk_msg_handler"
]
