[package]
name = "bulk_msg_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
interfaces = { path = "../../libs/interfaces" }
common = { path = "../../libs/common" }
message_structure = { path = "../../libs/message_structure" }